apiVersion: v1
kind: Secret
metadata:
  name: {{ include "social.fullname" . }}-env
data:
  {{ if .Values.connexion.server }}
  CONNEXION_SERVER: {{ .Values.connexion.server | b64enc }}
  {{- end }}
  {{ if .Values.connexion.debug }}
  CONNEXION_DEBUG: {{ .Values.connexion.debug | b64enc }}
  {{- end }}
  {{ if .Values.connexion.port }}
  CONNEXION_PORT: {{ .Values.connexion.port | b64enc}}
  {{- end }}
  {{ if .Values.connexion.keyfile }}
  CONNEXION_KEY_FILE: {{ .Values.connexion.keyfile | b64enc }}
  {{- end }}
  {{ if .Values.connexion.certfile }}
  CONNEXION_CERT_FILE: {{ .Values.connexion.certfile | b64enc }}
  {{- end }}
  {{ if .Values.sysPath.exposures }}
  EXPOSURES: {{ .Values.sysPath.exposures | b64enc }}
  {{- end }}
  {{ if .Values.sysPath.controllers }}
  CONTROLLERS: {{ .Values.sysPath.controllers | b64enc }}
  {{- end }}
  {{ if .Values.postgres.host }}
  POSTGRES_HOST: {{ .Values.postgres.host | b64enc }}
  {{- end }}
  {{ if .Values.postgres.port }}
  POSTGRES_PORT: {{ .Values.postgres.port | b64enc }}
  {{- end }}
  {{ if .Values.postgres.database }}
  POSTGRES_DATABASE: {{ .Values.postgres.port | b64enc }}
  {{- end }}
  {{ if .Values.postgres.username }}
  POSTGRES_USERNAME: {{ .Values.postgres.username | b64enc }}
  {{- end }}
  {{ if .Values.postgres.password }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc }}
  {{- end }}